=== HectorSanchezLuque/FirstYear/Lenguaje de marcas/Alex/ej8xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ej8xsd" xmlns:tns="http://www.example.org/ej8xsd" elementFormDefault="qualified">
<xs:element name="alumnos">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="alumno">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dni" type="xs:string"/>	
						<xs:element name="nombre" type="xs:string"/>
						<xs:element name="titulacion" type="xs:string"/>
						<xs:element name="curso_academico" type="xs:string"/>											
					</xs:sequence>
				</xs:complexType>
				<xs:element name="domicilios">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="domicilio">
								<xs:complexType>
								<xs:sequence>
									<xs:element name="calle" type="xs:string"/>
									<xs:element name="cp" type="xs:string"/>
									<xs:element name="poblacion" type="xs:string"/>
									<xs:element name="provincia" type="xs:string"/>
								</xs:sequence>
									<xs:atribute name="familiar" type="xs:string" use="required"/>
									<xs:atribute name="habitual" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>







</schema>

=== HectorSanchezLuque/FirstYear/Lenguaje de marcas/Alex/ej8xsd.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>


<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ej8xsd.xsd">
	<alumno>
		<dni>12345678X</dni>
		<nombre>Inés García Martín</nombre>
		<titulacion>Técnico Superior en DAM</titulacion>
		<curso_academico>2016/2017</curso_academico>
		<domicilios>
			<domicilio tipo="familiar">
				<calle>C/ Perú, no 7, 5o C</calle>
				<cp>15010</cp>
				<poblacion>A Coruña</poblacion>
				<provincia>A Coruña</provincia>
			</domicilio>
			<domicilio tipo="habitual">
				<calle>C/ Abeleira, no 3, 4o</calle>
				<cp>15679</cp>
				<poblacion>O Temple</poblacion>
				<provincia>A Coruña</provincia>
			</domicilio>
		</domicilios>
	</alumno>
</alumnos>
